/* DO NOT MODIFY, AUTOGENERATED */
/* GENERATED BY KODARPC CLI AT SAT MAY 11 2024 04:04:55 GMT+0300 (MOSCOW STANDARD TIME) */
export interface IPet {
    id: number;
    name: string;
    hello: boolean;
    pet: IPet;
}
export interface IPetService {
    getById(id: number): IPet;
}